-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS auth.audit_log_entries
(
    instance_id uuid,
    id uuid NOT NULL,
    payload json,
    created_at timestamp with time zone,
    ip_address character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    CONSTRAINT audit_log_entries_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.audit_log_entries
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.audit_log_entries
    IS 'Auth: Audit trail for user actions.';

CREATE TABLE IF NOT EXISTS auth.flow_state
(
    id uuid NOT NULL,
    user_id uuid,
    auth_code text COLLATE pg_catalog."default" NOT NULL,
    code_challenge_method auth.code_challenge_method NOT NULL,
    code_challenge text COLLATE pg_catalog."default" NOT NULL,
    provider_type text COLLATE pg_catalog."default" NOT NULL,
    provider_access_token text COLLATE pg_catalog."default",
    provider_refresh_token text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    authentication_method text COLLATE pg_catalog."default" NOT NULL,
    auth_code_issued_at timestamp with time zone,
    CONSTRAINT flow_state_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.flow_state
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.flow_state
    IS 'stores metadata for pkce logins';

CREATE TABLE IF NOT EXISTS auth.identities
(
    provider_id text COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    identity_data jsonb NOT NULL,
    provider text COLLATE pg_catalog."default" NOT NULL,
    last_sign_in_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    email text COLLATE pg_catalog."default" GENERATED ALWAYS AS (lower((identity_data ->> 'email'::text))) STORED,
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    CONSTRAINT identities_pkey PRIMARY KEY (id),
    CONSTRAINT identities_provider_id_provider_unique UNIQUE (provider_id, provider)
);

ALTER TABLE IF EXISTS auth.identities
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.identities
    IS 'Auth: Stores identities associated to a user.';

COMMENT ON COLUMN auth.identities.email
    IS 'Auth: Email is a generated column that references the optional email property in the identity_data';

CREATE TABLE IF NOT EXISTS auth.instances
(
    id uuid NOT NULL,
    uuid uuid,
    raw_base_config text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT instances_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.instances
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.instances
    IS 'Auth: Manages users across multiple sites.';

CREATE TABLE IF NOT EXISTS auth.mfa_amr_claims
(
    session_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    authentication_method text COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    CONSTRAINT amr_id_pk PRIMARY KEY (id),
    CONSTRAINT mfa_amr_claims_session_id_authentication_method_pkey UNIQUE (session_id, authentication_method)
);

ALTER TABLE IF EXISTS auth.mfa_amr_claims
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.mfa_amr_claims
    IS 'auth: stores authenticator method reference claims for multi factor authentication';

CREATE TABLE IF NOT EXISTS auth.mfa_challenges
(
    id uuid NOT NULL,
    factor_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    verified_at timestamp with time zone,
    ip_address inet NOT NULL,
    otp_code text COLLATE pg_catalog."default",
    web_authn_session_data jsonb,
    CONSTRAINT mfa_challenges_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.mfa_challenges
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.mfa_challenges
    IS 'auth: stores metadata about challenge requests made';

CREATE TABLE IF NOT EXISTS auth.mfa_factors
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    friendly_name text COLLATE pg_catalog."default",
    factor_type auth.factor_type NOT NULL,
    status auth.factor_status NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    secret text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    last_challenged_at timestamp with time zone,
    web_authn_credential jsonb,
    web_authn_aaguid uuid,
    last_webauthn_challenge_data jsonb,
    CONSTRAINT mfa_factors_pkey PRIMARY KEY (id),
    CONSTRAINT mfa_factors_last_challenged_at_key UNIQUE (last_challenged_at)
);

ALTER TABLE IF EXISTS auth.mfa_factors
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.mfa_factors
    IS 'auth: stores metadata about factors';

COMMENT ON COLUMN auth.mfa_factors.last_webauthn_challenge_data
    IS 'Stores the latest WebAuthn challenge data including attestation/assertion for customer verification';

CREATE TABLE IF NOT EXISTS auth.oauth_authorizations
(
    id uuid NOT NULL,
    authorization_id text COLLATE pg_catalog."default" NOT NULL,
    client_id uuid NOT NULL,
    user_id uuid,
    redirect_uri text COLLATE pg_catalog."default" NOT NULL,
    scope text COLLATE pg_catalog."default" NOT NULL,
    state text COLLATE pg_catalog."default",
    resource text COLLATE pg_catalog."default",
    code_challenge text COLLATE pg_catalog."default",
    code_challenge_method auth.code_challenge_method,
    response_type auth.oauth_response_type NOT NULL DEFAULT 'code'::auth.oauth_response_type,
    status auth.oauth_authorization_status NOT NULL DEFAULT 'pending'::auth.oauth_authorization_status,
    authorization_code text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:03:00'::interval),
    approved_at timestamp with time zone,
    CONSTRAINT oauth_authorizations_pkey PRIMARY KEY (id),
    CONSTRAINT oauth_authorizations_authorization_code_key UNIQUE (authorization_code),
    CONSTRAINT oauth_authorizations_authorization_id_key UNIQUE (authorization_id)
);

CREATE TABLE IF NOT EXISTS auth.oauth_clients
(
    id uuid NOT NULL,
    client_secret_hash text COLLATE pg_catalog."default",
    registration_type auth.oauth_registration_type NOT NULL,
    redirect_uris text COLLATE pg_catalog."default" NOT NULL,
    grant_types text COLLATE pg_catalog."default" NOT NULL,
    client_name text COLLATE pg_catalog."default",
    client_uri text COLLATE pg_catalog."default",
    logo_uri text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    client_type auth.oauth_client_type NOT NULL DEFAULT 'confidential'::auth.oauth_client_type,
    CONSTRAINT oauth_clients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS auth.oauth_consents
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    client_id uuid NOT NULL,
    scopes text COLLATE pg_catalog."default" NOT NULL,
    granted_at timestamp with time zone NOT NULL DEFAULT now(),
    revoked_at timestamp with time zone,
    CONSTRAINT oauth_consents_pkey PRIMARY KEY (id),
    CONSTRAINT oauth_consents_user_client_unique UNIQUE (user_id, client_id)
);

CREATE TABLE IF NOT EXISTS auth.one_time_tokens
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_type auth.one_time_token_type NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    relates_to text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT one_time_tokens_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.one_time_tokens
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS auth.refresh_tokens
(
    instance_id uuid,
    id bigserial NOT NULL,
    token character varying(255) COLLATE pg_catalog."default",
    user_id character varying(255) COLLATE pg_catalog."default",
    revoked boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    parent character varying(255) COLLATE pg_catalog."default",
    session_id uuid,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_token_unique UNIQUE (token)
);

ALTER TABLE IF EXISTS auth.refresh_tokens
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.refresh_tokens
    IS 'Auth: Store of tokens used to refresh JWT tokens once they expire.';

CREATE TABLE IF NOT EXISTS auth.saml_providers
(
    id uuid NOT NULL,
    sso_provider_id uuid NOT NULL,
    entity_id text COLLATE pg_catalog."default" NOT NULL,
    metadata_xml text COLLATE pg_catalog."default" NOT NULL,
    metadata_url text COLLATE pg_catalog."default",
    attribute_mapping jsonb,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    name_id_format text COLLATE pg_catalog."default",
    CONSTRAINT saml_providers_pkey PRIMARY KEY (id),
    CONSTRAINT saml_providers_entity_id_key UNIQUE (entity_id)
);

ALTER TABLE IF EXISTS auth.saml_providers
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.saml_providers
    IS 'Auth: Manages SAML Identity Provider connections.';

CREATE TABLE IF NOT EXISTS auth.saml_relay_states
(
    id uuid NOT NULL,
    sso_provider_id uuid NOT NULL,
    request_id text COLLATE pg_catalog."default" NOT NULL,
    for_email text COLLATE pg_catalog."default",
    redirect_to text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    flow_state_id uuid,
    CONSTRAINT saml_relay_states_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.saml_relay_states
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.saml_relay_states
    IS 'Auth: Contains SAML Relay State information for each Service Provider initiated login.';

CREATE TABLE IF NOT EXISTS auth.schema_migrations
(
    version character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);

ALTER TABLE IF EXISTS auth.schema_migrations
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.schema_migrations
    IS 'Auth: Manages updates to the auth system.';

CREATE TABLE IF NOT EXISTS auth.sessions
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    factor_id uuid,
    aal auth.aal_level,
    not_after timestamp with time zone,
    refreshed_at timestamp without time zone,
    user_agent text COLLATE pg_catalog."default",
    ip inet,
    tag text COLLATE pg_catalog."default",
    oauth_client_id uuid,
    refresh_token_hmac_key text COLLATE pg_catalog."default",
    refresh_token_counter bigint,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.sessions
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.sessions
    IS 'Auth: Stores session data associated to a user.';

COMMENT ON COLUMN auth.sessions.not_after
    IS 'Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.';

COMMENT ON COLUMN auth.sessions.refresh_token_hmac_key
    IS 'Holds a HMAC-SHA256 key used to sign refresh tokens for this session.';

COMMENT ON COLUMN auth.sessions.refresh_token_counter
    IS 'Holds the ID (counter) of the last issued refresh token.';

CREATE TABLE IF NOT EXISTS auth.sso_domains
(
    id uuid NOT NULL,
    sso_provider_id uuid NOT NULL,
    domain text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT sso_domains_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.sso_domains
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.sso_domains
    IS 'Auth: Manages SSO email address domain mapping to an SSO Identity Provider.';

CREATE TABLE IF NOT EXISTS auth.sso_providers
(
    id uuid NOT NULL,
    resource_id text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    disabled boolean,
    CONSTRAINT sso_providers_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS auth.sso_providers
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.sso_providers
    IS 'Auth: Manages SSO identity provider information; see saml_providers for SAML.';

COMMENT ON COLUMN auth.sso_providers.resource_id
    IS 'Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.';

CREATE TABLE IF NOT EXISTS auth.users
(
    instance_id uuid,
    id uuid NOT NULL,
    aud character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    encrypted_password character varying(255) COLLATE pg_catalog."default",
    email_confirmed_at timestamp with time zone,
    invited_at timestamp with time zone,
    confirmation_token character varying(255) COLLATE pg_catalog."default",
    confirmation_sent_at timestamp with time zone,
    recovery_token character varying(255) COLLATE pg_catalog."default",
    recovery_sent_at timestamp with time zone,
    email_change_token_new character varying(255) COLLATE pg_catalog."default",
    email_change character varying(255) COLLATE pg_catalog."default",
    email_change_sent_at timestamp with time zone,
    last_sign_in_at timestamp with time zone,
    raw_app_meta_data jsonb,
    raw_user_meta_data jsonb,
    is_super_admin boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    phone text COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    phone_confirmed_at timestamp with time zone,
    phone_change text COLLATE pg_catalog."default" DEFAULT ''::character varying,
    phone_change_token character varying(255) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    phone_change_sent_at timestamp with time zone,
    confirmed_at timestamp with time zone GENERATED ALWAYS AS (LEAST(email_confirmed_at, phone_confirmed_at)) STORED,
    email_change_token_current character varying(255) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    email_change_confirm_status smallint DEFAULT 0,
    banned_until timestamp with time zone,
    reauthentication_token character varying(255) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    reauthentication_sent_at timestamp with time zone,
    is_sso_user boolean NOT NULL DEFAULT false,
    deleted_at timestamp with time zone,
    is_anonymous boolean NOT NULL DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_phone_key UNIQUE (phone)
);

ALTER TABLE IF EXISTS auth.users
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE auth.users
    IS 'Auth: Stores user login data within a secure schema.';

COMMENT ON COLUMN auth.users.is_sso_user
    IS 'Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.';

CREATE TABLE IF NOT EXISTS public."Administrativo"
(
    administrativo_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    nombre_completo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    rut character varying(12) COLLATE pg_catalog."default",
    area_id smallint NOT NULL,
    cargo character varying(100) COLLATE pg_catalog."default",
    telefono character varying(15) COLLATE pg_catalog."default",
    fecha_contratacion date,
    estado_activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Administrativo_pkey" PRIMARY KEY (administrativo_id),
    CONSTRAINT "Administrativo_rut_key" UNIQUE (rut)
);

ALTER TABLE IF EXISTS public."Administrativo"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Alerta"
(
    alerta_id serial NOT NULL,
    tipo_alerta_id integer NOT NULL,
    estudiante_id uuid,
    profesor_id uuid,
    administrativo_id uuid,
    evento_id integer,
    titulo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    mensaje text COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now(),
    fecha_vencimiento timestamp without time zone,
    estado estado_alerta_enum DEFAULT 'PENDIENTE'::estado_alerta_enum,
    prioridad smallint DEFAULT 3,
    creado_por uuid,
    resuelto_por uuid,
    fecha_resolucion timestamp without time zone,
    observaciones_resolucion text COLLATE pg_catalog."default",
    CONSTRAINT "Alerta_pkey" PRIMARY KEY (alerta_id)
);

ALTER TABLE IF EXISTS public."Alerta"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."AnioAcademico"
(
    anio_id serial NOT NULL,
    colegio_id uuid NOT NULL,
    anio integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_termino date NOT NULL,
    primer_semestre_inicio date,
    primer_semestre_fin date,
    segundo_semestre_inicio date,
    segundo_semestre_fin date,
    vacaciones_invierno_inicio date,
    vacaciones_invierno_fin date,
    estado_activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "AnioAcademico_pkey" PRIMARY KEY (anio_id),
    CONSTRAINT "AnioAcademico_colegio_id_anio_key" UNIQUE (colegio_id, anio)
);

CREATE TABLE IF NOT EXISTS public."Anotaciones"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    estudiante_id uuid NOT NULL DEFAULT gen_random_uuid(),
    fecha timestamp without time zone NOT NULL,
    tipo_anotacion character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    profesor_id uuid DEFAULT gen_random_uuid(),
    CONSTRAINT "Anotaciones_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Anotaciones"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Area"
(
    area_id smallserial NOT NULL,
    nombre_area character varying(100) COLLATE pg_catalog."default" NOT NULL,
    colegio_id uuid NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    jefe_area_id uuid,
    CONSTRAINT "Area_pkey" PRIMARY KEY (area_id)
);

CREATE TABLE IF NOT EXISTS public."AsignacionAsiento"
(
    asignacion_id serial NOT NULL,
    estudiante_id uuid NOT NULL,
    curso_id uuid NOT NULL,
    sala_id character varying(20) COLLATE pg_catalog."default",
    num_asiento smallint,
    fecha_asignacion date,
    es_actual boolean DEFAULT true,
    CONSTRAINT "AsignacionAsiento_pkey" PRIMARY KEY (asignacion_id)
);

CREATE TABLE IF NOT EXISTS public."Asignatura"
(
    asignatura_id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    codigo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    profesor_id uuid NOT NULL,
    sala_id character varying(20) COLLATE pg_catalog."default",
    curso_id uuid NOT NULL,
    tipo_asignatura_id smallint,
    creditos smallint DEFAULT 1,
    horas_semanales smallint DEFAULT 2,
    descripcion text COLLATE pg_catalog."default",
    periodo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    estado_activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    materia_id bigint,
    CONSTRAINT "Asignatura_pkey" PRIMARY KEY (asignatura_id)
);

ALTER TABLE IF EXISTS public."Asignatura"
    ENABLE ROW LEVEL SECURITY;

COMMENT ON COLUMN public."Asignatura".materia_id
    IS 'Identificador único de una materia asociada a una asignatura.';

CREATE TABLE IF NOT EXISTS public."Asistencia"
(
    asistencia_id serial NOT NULL,
    fecha date NOT NULL,
    estudiante_id uuid NOT NULL,
    asignatura_id uuid NOT NULL,
    presente boolean NOT NULL DEFAULT false,
    retraso_minutos integer DEFAULT 0,
    retiro_anticipado_minutos integer DEFAULT 0,
    justificado boolean DEFAULT false,
    observaciones text COLLATE pg_catalog."default",
    registrado_por uuid,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Asistencia_pkey" PRIMARY KEY (asistencia_id),
    CONSTRAINT "Asistencia_fecha_estudiante_id_asignatura_id_key" UNIQUE (fecha, estudiante_id, asignatura_id)
);

ALTER TABLE IF EXISTS public."Asistencia"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."AuditoriaAcciones"
(
    auditoria_id bigserial NOT NULL,
    usuario_id uuid,
    tabla_afectada character varying(100) COLLATE pg_catalog."default" NOT NULL,
    registro_id character varying(100) COLLATE pg_catalog."default",
    accion character varying(20) COLLATE pg_catalog."default" NOT NULL,
    datos_anteriores jsonb,
    datos_nuevos jsonb,
    timestamp_accion timestamp without time zone DEFAULT now(),
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    CONSTRAINT "AuditoriaAcciones_pkey" PRIMARY KEY (auditoria_id)
);

CREATE TABLE IF NOT EXISTS public."Colegiatura"
(
    colegiatura_id uuid NOT NULL DEFAULT gen_random_uuid(),
    matricula_id uuid NOT NULL,
    mes smallint NOT NULL,
    anio smallint NOT NULL,
    monto integer NOT NULL,
    fecha_vencimiento date NOT NULL,
    fecha_pago timestamp without time zone,
    metodo_pago character varying(50) COLLATE pg_catalog."default",
    numero_comprobante character varying(100) COLLATE pg_catalog."default",
    estado estado_colegiatura_enum DEFAULT 'PENDIENTE'::estado_colegiatura_enum,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Colegiatura_pkey" PRIMARY KEY (colegiatura_id)
);

CREATE TABLE IF NOT EXISTS public."Colegio"
(
    colegio_id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default",
    fecha_creacion date NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    comuna character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Colegio_pkey" PRIMARY KEY (colegio_id)
);

ALTER TABLE IF EXISTS public."Colegio"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."ConfiguracionColegio"
(
    config_id uuid NOT NULL DEFAULT gen_random_uuid(),
    colegio_id uuid NOT NULL,
    clave character varying(100) COLLATE pg_catalog."default" NOT NULL,
    valor text COLLATE pg_catalog."default",
    tipo character varying(20) COLLATE pg_catalog."default" DEFAULT 'STRING'::character varying,
    descripcion text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "ConfiguracionColegio_pkey" PRIMARY KEY (config_id),
    CONSTRAINT "ConfiguracionColegio_colegio_id_clave_key" UNIQUE (colegio_id, clave)
);

CREATE TABLE IF NOT EXISTS public."Contrato"
(
    id_contrato bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    id_empleado uuid NOT NULL DEFAULT gen_random_uuid(),
    id_profesion bigint NOT NULL,
    inicio_contrato date NOT NULL,
    de_planta boolean NOT NULL DEFAULT false,
    termino_contrato date,
    CONSTRAINT "Contrato_pkey" PRIMARY KEY (id_contrato),
    CONSTRAINT "Contrato_id_contrato_key" UNIQUE (id_contrato)
);

ALTER TABLE IF EXISTS public."Contrato"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Curso"
(
    curso_id uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nivel_id bigint NOT NULL,
    generacion smallint NOT NULL,
    capacidad_maxima smallint DEFAULT 35,
    anio_academico integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    profesor_jefe_id uuid,
    CONSTRAINT "Curso_pkey" PRIMARY KEY (curso_id)
);

COMMENT ON COLUMN public."Curso".profesor_jefe_id
    IS 'ID del profesor jefe asignado al curso';

CREATE TABLE IF NOT EXISTS public."DatosEstudiante"
(
    estudiante_id uuid NOT NULL,
    encuesta_id uuid NOT NULL,
    contenido jsonb NOT NULL,
    contestado_en date NOT NULL,
    contestada_correctemente boolean,
    contestado_por uuid,
    CONSTRAINT "DatosEstudiante_pkey" PRIMARY KEY (estudiante_id)
);

CREATE TABLE IF NOT EXISTS public."Encuesta"
(
    encuesta_id uuid NOT NULL,
    tipo_encuesta_id smallint NOT NULL,
    titulo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    dirigida_a dirigida_a_encuesta_enum NOT NULL,
    template_encuesta jsonb,
    estado_activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Encuesta_pkey" PRIMARY KEY (encuesta_id)
);

CREATE TABLE IF NOT EXISTS public."Encuesta_Estudiante"
(
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    estudiante_id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_encuesta uuid NOT NULL,
    respuesta_encuesta jsonb NOT NULL,
    fecha_respuesta timestamp without time zone,
    CONSTRAINT "Encuesta_Estudiante_pkey" PRIMARY KEY (estudiante_id, id_encuesta)
);

ALTER TABLE IF EXISTS public."Encuesta_Estudiante"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Encuesta_Evaluacion"
(
    resultado_id smallserial NOT NULL,
    encuesta_id uuid,
    contenido jsonb,
    contestada_en date,
    CONSTRAINT "Encuesta_Evaluacion_pkey" PRIMARY KEY (resultado_id)
);

CREATE TABLE IF NOT EXISTS public."Especialidad"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    nombre_especialidad character varying COLLATE pg_catalog."default" NOT NULL,
    tipo_especialidad character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Especialidad_pkey" PRIMARY KEY (id),
    CONSTRAINT "Especialidad_id_key" UNIQUE (id)
);

ALTER TABLE IF EXISTS public."Especialidad"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."EstadoMatricula"
(
    estado_matricula_id smallserial NOT NULL,
    nombre_estado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(150) COLLATE pg_catalog."default",
    permite_asistencia boolean DEFAULT true,
    permite_evaluaciones boolean DEFAULT true,
    CONSTRAINT "EstadoMatricula_pkey" PRIMARY KEY (estado_matricula_id)
);

CREATE TABLE IF NOT EXISTS public."Estudiante"
(
    estudiante_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    nombre_completo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date NOT NULL,
    rut character varying(12) COLLATE pg_catalog."default" NOT NULL,
    genero genero_enum NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    estado_activo boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    comuna character varying COLLATE pg_catalog."default",
    foto_url text COLLATE pg_catalog."default",
    CONSTRAINT "Estudiante_pkey" PRIMARY KEY (estudiante_id),
    CONSTRAINT "Estudiante_rut_key" UNIQUE (rut)
);

ALTER TABLE IF EXISTS public."Estudiante"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Estudiante_Curso"
(
    estudiante_id uuid NOT NULL,
    curso_id uuid NOT NULL,
    periodo_cursado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_ingreso date NOT NULL DEFAULT CURRENT_DATE,
    fecha_retiro date,
    estado estado_estudiante_curso_enum DEFAULT 'ACTIVO'::estado_estudiante_curso_enum,
    promedio_final numeric(4, 2),
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Estudiante_Curso_pkey" PRIMARY KEY (estudiante_id, curso_id, periodo_cursado)
);

CREATE TABLE IF NOT EXISTS public."Evaluacion"
(
    evaluacion_id serial NOT NULL,
    asignatura_id uuid NOT NULL,
    encuesta_id uuid,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    tipo tipo_evaluacion_enum NOT NULL,
    fecha_evaluacion date NOT NULL,
    puntaje_maximo smallint NOT NULL,
    porcentaje_nota numeric(5, 2) NOT NULL DEFAULT 100,
    contenido jsonb,
    is_recuperativa boolean NOT NULL DEFAULT false,
    estado_activo boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "Evaluacion_pkey" PRIMARY KEY (evaluacion_id)
);

ALTER TABLE IF EXISTS public."Evaluacion"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Evento"
(
    evento_id serial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default",
    lugar character varying(255) COLLATE pg_catalog."default",
    fecha_inicio timestamp without time zone,
    fecha_fin timestamp without time zone,
    creado_por uuid,
    modificado_en timestamp without time zone,
    modificado_por uuid,
    CONSTRAINT "Evento_pkey" PRIMARY KEY (evento_id)
);

CREATE TABLE IF NOT EXISTS public."Grupo_taller"
(
    grupo_id serial NOT NULL,
    taller_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    estudiante_id uuid NOT NULL,
    fecha_inscripcion date NOT NULL DEFAULT CURRENT_DATE,
    fecha_retiro date,
    estado estado_taller_enum DEFAULT 'ACTIVO'::estado_taller_enum,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Grupo_taller_pkey" PRIMARY KEY (grupo_id),
    CONSTRAINT "Grupo_taller_taller_id_estudiante_id_key" UNIQUE (taller_id, estudiante_id)
);

CREATE TABLE IF NOT EXISTS public."Horario"
(
    horario_id serial NOT NULL,
    asignatura_id uuid NOT NULL,
    dia_semana smallint NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_termino time without time zone NOT NULL,
    sala_id character varying(20) COLLATE pg_catalog."default",
    periodo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    estado_activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Horario_pkey" PRIMARY KEY (horario_id),
    CONSTRAINT "Horario_asignatura_id_dia_semana_hora_inicio_periodo_key" UNIQUE (asignatura_id, dia_semana, hora_inicio, periodo)
);

CREATE TABLE IF NOT EXISTS public."Materia"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT "Materia_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Materia"
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public."Materia"
    IS 'Materias asignables a una asignatura';

CREATE TABLE IF NOT EXISTS public."Matricula"
(
    matricula_id uuid NOT NULL DEFAULT gen_random_uuid(),
    estudiante_id uuid NOT NULL,
    tutor_titular_id uuid NOT NULL,
    curso_id uuid NOT NULL,
    periodo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_matricula date NOT NULL DEFAULT CURRENT_DATE,
    fecha_pago date,
    monto_matricula integer,
    estado_matricula_id smallint NOT NULL DEFAULT 1,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Matricula_pkey" PRIMARY KEY (matricula_id)
);

ALTER TABLE IF EXISTS public."Matricula"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."NivelCurso"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    nivel character varying COLLATE pg_catalog."default" NOT NULL,
    numero smallint NOT NULL,
    CONSTRAINT "NivelCurso_pkey" PRIMARY KEY (id),
    CONSTRAINT "NivelCurso_id_key" UNIQUE (id)
);

ALTER TABLE IF EXISTS public."NivelCurso"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Parentesco"
(
    tutor_id uuid NOT NULL,
    estudiante_id uuid NOT NULL,
    tipo_parentesco_id smallint NOT NULL,
    es_tutor_titular boolean DEFAULT false,
    es_contacto_emergencia boolean DEFAULT false,
    puede_retirar boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Parentesco_pkey" PRIMARY KEY (tutor_id, estudiante_id, tipo_parentesco_id)
);

CREATE TABLE IF NOT EXISTS public."Profesion"
(
    id_profesion bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    nombre character varying COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT "Profesion_pkey" PRIMARY KEY (id_profesion),
    CONSTRAINT "Profesion_id_profesion_key" UNIQUE (id_profesion),
    CONSTRAINT "Profesion_id_profesion_key1" UNIQUE (id_profesion)
);

ALTER TABLE IF EXISTS public."Profesion"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Profesor"
(
    profesor_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    nombre_completo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    rut character varying(12) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    estado_activo boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    direccion character varying COLLATE pg_catalog."default",
    comuna character varying COLLATE pg_catalog."default",
    CONSTRAINT "Profesor_pkey" PRIMARY KEY (profesor_id),
    CONSTRAINT "Profesor_rut_key" UNIQUE (rut)
);

ALTER TABLE IF EXISTS public."Profesor"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Profesor_especialidad"
(
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    especialidad_id bigint NOT NULL,
    profesor_id uuid NOT NULL DEFAULT gen_random_uuid(),
    certificado_url text COLLATE pg_catalog."default",
    fecha_certificacion date,
    CONSTRAINT "Profesor_especialidad_pkey" PRIMARY KEY (especialidad_id, profesor_id)
);

ALTER TABLE IF EXISTS public."Profesor_especialidad"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."ResultadoEvaluacion"
(
    resultado_id serial NOT NULL,
    evaluacion_id integer NOT NULL,
    estudiante_id uuid NOT NULL,
    puntaje_obtenido integer NOT NULL,
    nota numeric(4, 2),
    porcentaje numeric(5, 2),
    fecha_evaluacion timestamp without time zone DEFAULT now(),
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "ResultadoEvaluacion_pkey" PRIMARY KEY (resultado_id),
    CONSTRAINT "ResultadoEvaluacion_evaluacion_id_estudiante_id_key" UNIQUE (evaluacion_id, estudiante_id)
);

ALTER TABLE IF EXISTS public."ResultadoEvaluacion"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Sala"
(
    sala_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    zona_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    capacidad smallint DEFAULT 35,
    tiene_proyector boolean DEFAULT false,
    tiene_pizarra_digital boolean DEFAULT false,
    estado estado_sala_enum DEFAULT 'DISPONIBLE'::estado_sala_enum,
    distribucion_asientos_template jsonb,
    CONSTRAINT "Sala_pkey" PRIMARY KEY (sala_id)
);

CREATE TABLE IF NOT EXISTS public."Taller"
(
    taller_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    profesor_encargado_id uuid,
    capacidad_maxima smallint DEFAULT 25,
    horario character varying(100) COLLATE pg_catalog."default",
    sala_id character varying(20) COLLATE pg_catalog."default",
    costo_adicional integer DEFAULT 0,
    estado_activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "Taller_pkey" PRIMARY KEY (taller_id)
);

CREATE TABLE IF NOT EXISTS public."TipoAlerta"
(
    tipo_alerta_id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    nivel_prioridad smallint DEFAULT 3,
    color_hex character(7) COLLATE pg_catalog."default" DEFAULT '#FFD700'::bpchar,
    requiere_accion boolean DEFAULT false,
    estado_activo boolean DEFAULT true,
    CONSTRAINT "TipoAlerta_pkey" PRIMARY KEY (tipo_alerta_id)
);

CREATE TABLE IF NOT EXISTS public."TipoAsignatura"
(
    tipo_asignatura_id smallserial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default",
    descripcion character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "TipoAsignatura_pkey" PRIMARY KEY (tipo_asignatura_id)
);

CREATE TABLE IF NOT EXISTS public."TipoEncuesta"
(
    tipo_encuesta_id smallserial NOT NULL,
    nombre_tipo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado_activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "TipoEncuesta_pkey" PRIMARY KEY (tipo_encuesta_id)
);

CREATE TABLE IF NOT EXISTS public."Tipo_parentesco"
(
    tipo_parentesco_id smallserial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "Tipo_parentesco_pkey" PRIMARY KEY (tipo_parentesco_id)
);

CREATE TABLE IF NOT EXISTS public."Tutor"
(
    tutor_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    nombre_completo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    rut character varying(12) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ocupacion character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    estado_activo boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    comuna character varying COLLATE pg_catalog."default",
    CONSTRAINT "Tutor_pkey" PRIMARY KEY (tutor_id),
    CONSTRAINT "Tutor_rut_key" UNIQUE (rut)
);

ALTER TABLE IF EXISTS public."Tutor"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."User"
(
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    email_address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    last_login timestamp without time zone,
    auth_user_id uuid,
    profile_completed boolean DEFAULT false,
    role user_role_enum,
    colegio_id uuid,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT "User_pkey" PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public."User"
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."Zona"
(
    zona_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    colegio_id uuid NOT NULL,
    nombre_zona character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    capacidad_total smallint,
    CONSTRAINT "Zona_pkey" PRIMARY KEY (zona_id)
);

CREATE TABLE IF NOT EXISTS realtime.messages
(
    topic text COLLATE pg_catalog."default" NOT NULL,
    extension text COLLATE pg_catalog."default" NOT NULL,
    payload jsonb,
    event text COLLATE pg_catalog."default",
    private boolean DEFAULT false,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    inserted_at timestamp without time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    CONSTRAINT messages_pkey PRIMARY KEY (id, inserted_at)
);

ALTER TABLE IF EXISTS realtime.messages
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS realtime.schema_migrations
(
    version bigint NOT NULL,
    inserted_at timestamp(0) without time zone,
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);

CREATE TABLE IF NOT EXISTS realtime.subscription
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    subscription_id uuid NOT NULL,
    entity regclass NOT NULL,
    filters realtime.user_defined_filter[] NOT NULL DEFAULT '{}'::realtime.user_defined_filter[],
    claims jsonb NOT NULL,
    claims_role regrole NOT NULL GENERATED ALWAYS AS (realtime.to_regrole((claims ->> 'role'::text))) STORED,
    created_at timestamp without time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT pk_subscription PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS storage.buckets
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    owner uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    public boolean DEFAULT false,
    avif_autodetection boolean DEFAULT false,
    file_size_limit bigint,
    allowed_mime_types text[] COLLATE pg_catalog."default",
    owner_id text COLLATE pg_catalog."default",
    type storage.buckettype NOT NULL DEFAULT 'STANDARD'::storage.buckettype,
    CONSTRAINT buckets_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS storage.buckets
    ENABLE ROW LEVEL SECURITY;

COMMENT ON COLUMN storage.buckets.owner
    IS 'Field is deprecated, use owner_id instead';

CREATE TABLE IF NOT EXISTS storage.buckets_analytics
(
    name text COLLATE pg_catalog."default" NOT NULL,
    type storage.buckettype NOT NULL DEFAULT 'ANALYTICS'::storage.buckettype,
    format text COLLATE pg_catalog."default" NOT NULL DEFAULT 'ICEBERG'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    deleted_at timestamp with time zone,
    CONSTRAINT buckets_analytics_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS storage.buckets_analytics
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS storage.buckets_vectors
(
    id text COLLATE pg_catalog."default" NOT NULL,
    type storage.buckettype NOT NULL DEFAULT 'VECTOR'::storage.buckettype,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT buckets_vectors_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS storage.buckets_vectors
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS storage.migrations
(
    id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    hash character varying(40) COLLATE pg_catalog."default" NOT NULL,
    executed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT migrations_pkey PRIMARY KEY (id),
    CONSTRAINT migrations_name_key UNIQUE (name)
);

ALTER TABLE IF EXISTS storage.migrations
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS storage.objects
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    bucket_id text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    owner uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    last_accessed_at timestamp with time zone DEFAULT now(),
    metadata jsonb,
    path_tokens text[] COLLATE pg_catalog."default" GENERATED ALWAYS AS (string_to_array(name, '/'::text)) STORED,
    version text COLLATE pg_catalog."default",
    owner_id text COLLATE pg_catalog."default",
    user_metadata jsonb,
    level integer,
    CONSTRAINT objects_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS storage.objects
    ENABLE ROW LEVEL SECURITY;

COMMENT ON COLUMN storage.objects.owner
    IS 'Field is deprecated, use owner_id instead';

CREATE TABLE IF NOT EXISTS storage.prefixes
(
    bucket_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."C" NOT NULL,
    level integer NOT NULL GENERATED ALWAYS AS (storage.get_level(name)) STORED,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT prefixes_pkey PRIMARY KEY (bucket_id, level, name)
);

ALTER TABLE IF EXISTS storage.prefixes
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS storage.s3_multipart_uploads
(
    id text COLLATE pg_catalog."default" NOT NULL,
    in_progress_size bigint NOT NULL DEFAULT 0,
    upload_signature text COLLATE pg_catalog."default" NOT NULL,
    bucket_id text COLLATE pg_catalog."default" NOT NULL,
    key text COLLATE pg_catalog."C" NOT NULL,
    version text COLLATE pg_catalog."default" NOT NULL,
    owner_id text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_metadata jsonb,
    CONSTRAINT s3_multipart_uploads_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS storage.s3_multipart_uploads
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS storage.s3_multipart_uploads_parts
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    upload_id text COLLATE pg_catalog."default" NOT NULL,
    size bigint NOT NULL DEFAULT 0,
    part_number integer NOT NULL,
    bucket_id text COLLATE pg_catalog."default" NOT NULL,
    key text COLLATE pg_catalog."C" NOT NULL,
    etag text COLLATE pg_catalog."default" NOT NULL,
    owner_id text COLLATE pg_catalog."default",
    version text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT s3_multipart_uploads_parts_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS storage.s3_multipart_uploads_parts
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS storage.vector_indexes
(
    id text COLLATE pg_catalog."default" NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."C" NOT NULL,
    bucket_id text COLLATE pg_catalog."default" NOT NULL,
    data_type text COLLATE pg_catalog."default" NOT NULL,
    dimension integer NOT NULL,
    distance_metric text COLLATE pg_catalog."default" NOT NULL,
    metadata_configuration jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT vector_indexes_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS storage.vector_indexes
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS supabase_migrations.schema_migrations
(
    version text COLLATE pg_catalog."default" NOT NULL,
    statements text[] COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);

CREATE TABLE IF NOT EXISTS supabase_migrations.seed_files
(
    path text COLLATE pg_catalog."default" NOT NULL,
    hash text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT seed_files_pkey PRIMARY KEY (path)
);

ALTER TABLE IF EXISTS auth.identities
    ADD CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS identities_user_id_idx
    ON auth.identities(user_id);


ALTER TABLE IF EXISTS auth.mfa_amr_claims
    ADD CONSTRAINT mfa_amr_claims_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES auth.sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.mfa_challenges
    ADD CONSTRAINT mfa_challenges_auth_factor_id_fkey FOREIGN KEY (factor_id)
    REFERENCES auth.mfa_factors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.mfa_factors
    ADD CONSTRAINT mfa_factors_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS mfa_factors_user_id_idx
    ON auth.mfa_factors(user_id);


ALTER TABLE IF EXISTS auth.oauth_authorizations
    ADD CONSTRAINT oauth_authorizations_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES auth.oauth_clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.oauth_authorizations
    ADD CONSTRAINT oauth_authorizations_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.oauth_consents
    ADD CONSTRAINT oauth_consents_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES auth.oauth_clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS oauth_consents_active_client_idx
    ON auth.oauth_consents(client_id);


ALTER TABLE IF EXISTS auth.oauth_consents
    ADD CONSTRAINT oauth_consents_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.one_time_tokens
    ADD CONSTRAINT one_time_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.refresh_tokens
    ADD CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES auth.sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.saml_providers
    ADD CONSTRAINT saml_providers_sso_provider_id_fkey FOREIGN KEY (sso_provider_id)
    REFERENCES auth.sso_providers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS saml_providers_sso_provider_id_idx
    ON auth.saml_providers(sso_provider_id);


ALTER TABLE IF EXISTS auth.saml_relay_states
    ADD CONSTRAINT saml_relay_states_flow_state_id_fkey FOREIGN KEY (flow_state_id)
    REFERENCES auth.flow_state (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS auth.saml_relay_states
    ADD CONSTRAINT saml_relay_states_sso_provider_id_fkey FOREIGN KEY (sso_provider_id)
    REFERENCES auth.sso_providers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS saml_relay_states_sso_provider_id_idx
    ON auth.saml_relay_states(sso_provider_id);


ALTER TABLE IF EXISTS auth.sessions
    ADD CONSTRAINT sessions_oauth_client_id_fkey FOREIGN KEY (oauth_client_id)
    REFERENCES auth.oauth_clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS sessions_oauth_client_id_idx
    ON auth.sessions(oauth_client_id);


ALTER TABLE IF EXISTS auth.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS sessions_user_id_idx
    ON auth.sessions(user_id);


ALTER TABLE IF EXISTS auth.sso_domains
    ADD CONSTRAINT sso_domains_sso_provider_id_fkey FOREIGN KEY (sso_provider_id)
    REFERENCES auth.sso_providers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS sso_domains_sso_provider_id_idx
    ON auth.sso_domains(sso_provider_id);


ALTER TABLE IF EXISTS public."Administrativo"
    ADD CONSTRAINT "Administrativo_area_id_fkey" FOREIGN KEY (area_id)
    REFERENCES public."Area" (area_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Administrativo"
    ADD CONSTRAINT "Administrativo_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Alerta"
    ADD CONSTRAINT "Alerta_administrativo_id_fkey" FOREIGN KEY (administrativo_id)
    REFERENCES public."Administrativo" (administrativo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Alerta"
    ADD CONSTRAINT "Alerta_creado_por_fkey" FOREIGN KEY (creado_por)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Alerta"
    ADD CONSTRAINT "Alerta_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_alerta_estudiante
    ON public."Alerta"(estudiante_id);


ALTER TABLE IF EXISTS public."Alerta"
    ADD CONSTRAINT "Alerta_evento_id_fkey" FOREIGN KEY (evento_id)
    REFERENCES public."Evento" (evento_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Alerta"
    ADD CONSTRAINT "Alerta_profesor_id_fkey" FOREIGN KEY (profesor_id)
    REFERENCES public."Profesor" (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Alerta"
    ADD CONSTRAINT "Alerta_resuelto_por_fkey" FOREIGN KEY (resuelto_por)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Alerta"
    ADD CONSTRAINT "Alerta_tipo_alerta_id_fkey" FOREIGN KEY (tipo_alerta_id)
    REFERENCES public."TipoAlerta" (tipo_alerta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."AnioAcademico"
    ADD CONSTRAINT "AnioAcademico_colegio_id_fkey" FOREIGN KEY (colegio_id)
    REFERENCES public."Colegio" (colegio_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Anotaciones"
    ADD CONSTRAINT "Anotaciones_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Anotaciones"
    ADD CONSTRAINT "Anotaciones_profesor_id_fkey" FOREIGN KEY (profesor_id)
    REFERENCES public."Profesor" (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Area"
    ADD CONSTRAINT "Area_colegio_id_fkey" FOREIGN KEY (colegio_id)
    REFERENCES public."Colegio" (colegio_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Area"
    ADD CONSTRAINT fk_area_jefe FOREIGN KEY (jefe_area_id)
    REFERENCES public."Profesor" (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."AsignacionAsiento"
    ADD CONSTRAINT "AsignacionAsiento_curso_id_fkey" FOREIGN KEY (curso_id)
    REFERENCES public."Curso" (curso_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."AsignacionAsiento"
    ADD CONSTRAINT "AsignacionAsiento_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."AsignacionAsiento"
    ADD CONSTRAINT "AsignacionAsiento_sala_id_fkey" FOREIGN KEY (sala_id)
    REFERENCES public."Sala" (sala_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Asignatura"
    ADD CONSTRAINT "Asignatura_curso_id_fkey" FOREIGN KEY (curso_id)
    REFERENCES public."Curso" (curso_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Asignatura"
    ADD CONSTRAINT "Asignatura_materia_id_fkey" FOREIGN KEY (materia_id)
    REFERENCES public."Materia" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Asignatura"
    ADD CONSTRAINT "Asignatura_profesor_id_fkey" FOREIGN KEY (profesor_id)
    REFERENCES public."Profesor" (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Asignatura"
    ADD CONSTRAINT "Asignatura_sala_id_fkey" FOREIGN KEY (sala_id)
    REFERENCES public."Sala" (sala_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Asignatura"
    ADD CONSTRAINT "Asignatura_tipo_asignatura_id_fkey" FOREIGN KEY (tipo_asignatura_id)
    REFERENCES public."TipoAsignatura" (tipo_asignatura_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Asistencia"
    ADD CONSTRAINT "Asistencia_asignatura_id_fkey" FOREIGN KEY (asignatura_id)
    REFERENCES public."Asignatura" (asignatura_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_asistencia_asignatura
    ON public."Asistencia"(asignatura_id);


ALTER TABLE IF EXISTS public."Asistencia"
    ADD CONSTRAINT "Asistencia_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Asistencia"
    ADD CONSTRAINT "Asistencia_registrado_por_fkey" FOREIGN KEY (registrado_por)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."AuditoriaAcciones"
    ADD CONSTRAINT "AuditoriaAcciones_usuario_id_fkey" FOREIGN KEY (usuario_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Colegiatura"
    ADD CONSTRAINT "Colegiatura_matricula_id_fkey" FOREIGN KEY (matricula_id)
    REFERENCES public."Matricula" (matricula_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_colegiatura_matricula
    ON public."Colegiatura"(matricula_id);


ALTER TABLE IF EXISTS public."ConfiguracionColegio"
    ADD CONSTRAINT "ConfiguracionColegio_colegio_id_fkey" FOREIGN KEY (colegio_id)
    REFERENCES public."Colegio" (colegio_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Contrato"
    ADD CONSTRAINT "Contrato_id_empleado_fkey" FOREIGN KEY (id_empleado)
    REFERENCES public."Administrativo" (administrativo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Contrato"
    ADD CONSTRAINT "Contrato_id_empleado_fkey1" FOREIGN KEY (id_empleado)
    REFERENCES public."Profesor" (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Contrato"
    ADD CONSTRAINT "Contrato_id_profesion_fkey" FOREIGN KEY (id_profesion)
    REFERENCES public."Profesion" (id_profesion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Curso"
    ADD CONSTRAINT "Curso_nivel_id_fkey" FOREIGN KEY (nivel_id)
    REFERENCES public."NivelCurso" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Curso"
    ADD CONSTRAINT "Curso_profesor_jefe_id_fkey" FOREIGN KEY (profesor_jefe_id)
    REFERENCES public."Profesor" (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."DatosEstudiante"
    ADD CONSTRAINT "DatosEstudiante_contestado_por_fkey" FOREIGN KEY (contestado_por)
    REFERENCES public."Tutor" (tutor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."DatosEstudiante"
    ADD CONSTRAINT "DatosEstudiante_encuesta_id_fkey" FOREIGN KEY (encuesta_id)
    REFERENCES public."Encuesta" (encuesta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."DatosEstudiante"
    ADD CONSTRAINT "DatosEstudiante_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "DatosEstudiante_pkey"
    ON public."DatosEstudiante"(estudiante_id);


ALTER TABLE IF EXISTS public."Encuesta"
    ADD CONSTRAINT "Encuesta_tipo_encuesta_id_fkey" FOREIGN KEY (tipo_encuesta_id)
    REFERENCES public."TipoEncuesta" (tipo_encuesta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Encuesta_Estudiante"
    ADD CONSTRAINT "Encuesta_Estudiante_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Encuesta_Estudiante"
    ADD CONSTRAINT "Encuesta_Estudiante_id_encuesta_fkey" FOREIGN KEY (id_encuesta)
    REFERENCES public."Encuesta" (encuesta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Encuesta_Evaluacion"
    ADD CONSTRAINT "Encuesta_Evaluacion_encuesta_id_fkey" FOREIGN KEY (encuesta_id)
    REFERENCES public."Encuesta" (encuesta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Estudiante"
    ADD CONSTRAINT "Estudiante_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_estudiante_user
    ON public."Estudiante"(user_id);


ALTER TABLE IF EXISTS public."Estudiante_Curso"
    ADD CONSTRAINT "Estudiante_Curso_curso_id_fkey" FOREIGN KEY (curso_id)
    REFERENCES public."Curso" (curso_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Estudiante_Curso"
    ADD CONSTRAINT "Estudiante_Curso_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Evaluacion"
    ADD CONSTRAINT "Evaluacion_asignatura_id_fkey" FOREIGN KEY (asignatura_id)
    REFERENCES public."Asignatura" (asignatura_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_evaluacion_asignatura
    ON public."Evaluacion"(asignatura_id);


ALTER TABLE IF EXISTS public."Evaluacion"
    ADD CONSTRAINT "Evaluacion_encuesta_id_fkey" FOREIGN KEY (encuesta_id)
    REFERENCES public."Encuesta" (encuesta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."Evento"
    ADD CONSTRAINT "Evento_creado_por_fkey" FOREIGN KEY (creado_por)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Evento"
    ADD CONSTRAINT "Evento_modificado_por_fkey" FOREIGN KEY (modificado_por)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Grupo_taller"
    ADD CONSTRAINT "Grupo_taller_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Grupo_taller"
    ADD CONSTRAINT "Grupo_taller_taller_id_fkey" FOREIGN KEY (taller_id)
    REFERENCES public."Taller" (taller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Horario"
    ADD CONSTRAINT "Horario_asignatura_id_fkey" FOREIGN KEY (asignatura_id)
    REFERENCES public."Asignatura" (asignatura_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_horario_asignatura
    ON public."Horario"(asignatura_id);


ALTER TABLE IF EXISTS public."Horario"
    ADD CONSTRAINT "Horario_sala_id_fkey" FOREIGN KEY (sala_id)
    REFERENCES public."Sala" (sala_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Matricula"
    ADD CONSTRAINT "Matricula_curso_id_fkey" FOREIGN KEY (curso_id)
    REFERENCES public."Curso" (curso_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Matricula"
    ADD CONSTRAINT "Matricula_estado_matricula_id_fkey" FOREIGN KEY (estado_matricula_id)
    REFERENCES public."EstadoMatricula" (estado_matricula_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_matricula_estado
    ON public."Matricula"(estado_matricula_id);


ALTER TABLE IF EXISTS public."Matricula"
    ADD CONSTRAINT "Matricula_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_matricula_estudiante
    ON public."Matricula"(estudiante_id);


ALTER TABLE IF EXISTS public."Matricula"
    ADD CONSTRAINT "Matricula_tutor_titular_id_fkey" FOREIGN KEY (tutor_titular_id)
    REFERENCES public."Tutor" (tutor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Parentesco"
    ADD CONSTRAINT "Parentesco_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Parentesco"
    ADD CONSTRAINT "Parentesco_tipo_parentesco_id_fkey" FOREIGN KEY (tipo_parentesco_id)
    REFERENCES public."Tipo_parentesco" (tipo_parentesco_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Parentesco"
    ADD CONSTRAINT "Parentesco_tutor_id_fkey" FOREIGN KEY (tutor_id)
    REFERENCES public."Tutor" (tutor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Profesor"
    ADD CONSTRAINT "Profesor_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_profesor_user
    ON public."Profesor"(user_id);


ALTER TABLE IF EXISTS public."Profesor_especialidad"
    ADD CONSTRAINT "Profesor_especialidad_especialidad_id_fkey" FOREIGN KEY (especialidad_id)
    REFERENCES public."Especialidad" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Profesor_especialidad"
    ADD CONSTRAINT "Profesor_especialidad_profesor_id_fkey" FOREIGN KEY (profesor_id)
    REFERENCES public."Profesor" (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."ResultadoEvaluacion"
    ADD CONSTRAINT "ResultadoEvaluacion_estudiante_id_fkey" FOREIGN KEY (estudiante_id)
    REFERENCES public."Estudiante" (estudiante_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_resultado_estudiante
    ON public."ResultadoEvaluacion"(estudiante_id);


ALTER TABLE IF EXISTS public."ResultadoEvaluacion"
    ADD CONSTRAINT "ResultadoEvaluacion_evaluacion_id_fkey" FOREIGN KEY (evaluacion_id)
    REFERENCES public."Evaluacion" (evaluacion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_resultado_evaluacion
    ON public."ResultadoEvaluacion"(evaluacion_id);


ALTER TABLE IF EXISTS public."Sala"
    ADD CONSTRAINT "Sala_zona_id_fkey" FOREIGN KEY (zona_id)
    REFERENCES public."Zona" (zona_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Taller"
    ADD CONSTRAINT "Taller_profesor_encargado_id_fkey" FOREIGN KEY (profesor_encargado_id)
    REFERENCES public."Profesor" (profesor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Taller"
    ADD CONSTRAINT "Taller_sala_id_fkey" FOREIGN KEY (sala_id)
    REFERENCES public."Sala" (sala_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Tutor"
    ADD CONSTRAINT "Tutor_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_tutor_user
    ON public."Tutor"(user_id);


ALTER TABLE IF EXISTS public."User"
    ADD CONSTRAINT "User_auth_user_id_fkey" FOREIGN KEY (auth_user_id)
    REFERENCES auth.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_auth_id
    ON public."User"(auth_user_id);


ALTER TABLE IF EXISTS public."User"
    ADD CONSTRAINT "User_colegio_id_fkey" FOREIGN KEY (colegio_id)
    REFERENCES public."Colegio" (colegio_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_user_colegio
    ON public."User"(colegio_id);


ALTER TABLE IF EXISTS public."Zona"
    ADD CONSTRAINT "Zona_colegio_id_fkey" FOREIGN KEY (colegio_id)
    REFERENCES public."Colegio" (colegio_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS storage.objects
    ADD CONSTRAINT "objects_bucketId_fkey" FOREIGN KEY (bucket_id)
    REFERENCES storage.buckets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS storage.prefixes
    ADD CONSTRAINT "prefixes_bucketId_fkey" FOREIGN KEY (bucket_id)
    REFERENCES storage.buckets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS storage.s3_multipart_uploads
    ADD CONSTRAINT s3_multipart_uploads_bucket_id_fkey FOREIGN KEY (bucket_id)
    REFERENCES storage.buckets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS storage.s3_multipart_uploads_parts
    ADD CONSTRAINT s3_multipart_uploads_parts_bucket_id_fkey FOREIGN KEY (bucket_id)
    REFERENCES storage.buckets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS storage.s3_multipart_uploads_parts
    ADD CONSTRAINT s3_multipart_uploads_parts_upload_id_fkey FOREIGN KEY (upload_id)
    REFERENCES storage.s3_multipart_uploads (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS storage.vector_indexes
    ADD CONSTRAINT vector_indexes_bucket_id_fkey FOREIGN KEY (bucket_id)
    REFERENCES storage.buckets_vectors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;